# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile


ifeq ($(OS),Windows_NT)
    # configuration
    ARDMK_DIR=../Arduino-Makefile/
    ARDUINO_DIR=../../../Arduino/
endif

BOARD_TAG    = uno

include ../Arduino-Makefile/Arduino.mk

